namespace MyPlatformModels.Models
{
    /// <summary>
    /// Represents file metadata in the domain
    /// </summary>
    public class FileMetadata
    {
        /// <summary>
        /// Unique identifier for the file (generated by MongoDB)
        /// </summary>
        public string? Id { get; set; }

        /// <summary>
        /// Original file name
        /// </summary>
        public required string FileName { get; set; }

        /// <summary>
        /// File extension (e.g., .jpg, .png, .mp3)
        /// </summary>
        public required string FileExtension { get; set; }

        /// <summary>
        /// MIME type of the file
        /// </summary>
        public required string ContentType { get; set; }

        /// <summary>
        /// Size of the file in bytes
        /// </summary>
        public long FileSizeBytes { get; set; }

        /// <summary>
        /// When the file was uploaded
        /// </summary>
        public DateTime UploadedAt { get; set; }

        /// <summary>
        /// Generic metadata dictionary for additional properties
        /// </summary>
        public Dictionary<string, string> Metadata { get; set; } = new Dictionary<string, string>();
    }
}
